name: spicy
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: '>=2.19.6 <3.0.0'



dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.4.0
  flutter_font_icons: ^2.2.5
  animate_do: ^3.0.2
  loading_animation_widget: ^1.2.0+4
  typewritertext: ^1.8.0
  blinking_text: ^1.0.2
  smooth_page_indicator: ^1.1.0
  liquid_swipe: ^3.1.0
  lottie: ^2.3.2
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/splash/
    - assets/images/onboarding/
    - assets/images/background/
    - assets/images/foods/
    - assets/icons/
    - assets/json/


  fonts:
    - family: Bruno
      fonts:
        - asset: assets/fonts/bruno/BrunoAceSC-Regular.ttf
    #
    - family: Pacifico
      fonts:
        - asset: assets/fonts/pacifico/Pacifico-Regular.ttf
    #
    - family: Metropolis
      fonts:
        - asset: assets/fonts/metropolis/Metropolis-Regular.ttf
          style: normal
        - asset: assets/fonts/metropolis/Metropolis-RegularItalic.ttf
          style: italic
        - asset: assets/fonts/metropolis/Metropolis-Medium.ttf
          weight: 500
        - asset: assets/fonts/metropolis/Metropolis-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/metropolis/Metropolis-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/metropolis/Metropolis-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/metropolis/Metropolis-Bold.ttf
          weight: 700
        - asset: assets/fonts/metropolis/Metropolis-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/metropolis/Metropolis-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/metropolis/Metropolis-ExtraBoldItalic.ttf
          style: italic
          weight: 900